#pragma once

#define NULL 0
#define SAFE_TEST_RET(REALVALUE, TESTVALUE) if((REALVALUE) == (TESTVALUE)) return;
#define SAFE_TEST_RET_VAL(REALVALUE, TESTVALUE, RETVALUE) if((REALVALUE) == (TESTVALUE)) return RETVALUE;